"""billing, presets, language

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-18 19:19:45.617561

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_presets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_search_presets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_presets")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_search_presets_user_id_name")),
    )
    op.create_index(op.f("ix_search_presets_user_id"), "search_presets", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_trial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("payment_provider", sa.String(length=16), nullable=True),
        sa.Column("payment_id", sa.String(length=64), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(
        "ix_subscriptions_user_ends_at", "subscriptions", ["user_id", "ends_at"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_index(
        "uq_subscriptions_payment",
        "subscriptions",
        ["payment_provider", "payment_id"],
        unique=True,
        postgresql_where=sa.text("payment_id IS NOT NULL"),
    )
    op.create_index(
        "uq_subscriptions_trial_per_user",
        "subscriptions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_trial"),
    )
    op.add_column("users", sa.Column("language_code", sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language_code")
    op.drop_index(
        "uq_subscriptions_trial_per_user",
        table_name="subscriptions",
        postgresql_where=sa.text("is_trial"),
    )
    op.drop_index(
        "uq_subscriptions_payment",
        table_name="subscriptions",
        postgresql_where=sa.text("payment_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_user_ends_at", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_search_presets_user_id"), table_name="search_presets")
    op.drop_table("search_presets")
    # ### end Alembic commands ###
