"""favorites, blocked sellers, listing details

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-19 00:15:17.089396

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_sellers",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("seller_id", sa.String(length=64), nullable=False),
        sa.Column("seller_name", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_blocked_sellers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "marketplace", "seller_id", name=op.f("pk_blocked_sellers")
        ),
    )
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_favorites_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "listing_id", name=op.f("pk_favorites")),
    )
    op.add_column(
        "listings",
        sa.Column(
            "images",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("listings", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("listings", sa.Column("seller_id", sa.String(length=64), nullable=True))
    op.add_column("listings", sa.Column("seller_name", sa.String(length=128), nullable=True))
    op.add_column(
        "listings",
        sa.Column("is_business", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "listings",
        sa.Column("has_delivery", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "listings", sa.Column("previous_price", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.create_index(op.f("ix_listings_seller_id"), "listings", ["seller_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_seller_id"), table_name="listings")
    op.drop_column("listings", "previous_price")
    op.drop_column("listings", "has_delivery")
    op.drop_column("listings", "is_business")
    op.drop_column("listings", "seller_name")
    op.drop_column("listings", "seller_id")
    op.drop_column("listings", "description")
    op.drop_column("listings", "images")
    op.drop_table("favorites")
    op.drop_table("blocked_sellers")
    # ### end Alembic commands ###
